development:
  adapter: sqlite3
  database: bromo-development.sqlite
  pool: 30
  checkout_timeout: 30000

test:
  adapter: sqlite3
  database: bromo-test.sqlite
  pool: 30
  checkout_timeout: 30000

production:
  adapter: mysql2
  pool: 30
  checkout_timeout: 30000
  encoding: utf8
  username: root
  database: bromo_production
  password: ~


