development:
  adapter: sqlite3
  database: bromo-development.sqlite
  pool: 30
  timeout: 10000

test:
  adapter: sqlite3
  database: bromo-test.sqlite
  pool: 30
  timeout: 10000

production:
  adapter: sqlite3
  database: bromo-production.sqlite
  pool: 30
  timeout: 10000

