development:
  adapter: sqlite3
  database: bromo-development.sqlite
  timeout: 30000

test:
  adapter: sqlite3
  database: bromo-test.sqlite
  timeout: 30000

production:
  adapter: sqlite3
  database: bromo-production.sqlite
  timeout: 30000

